# Generated by Django 4.1.6 on 2023-02-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=20)),
                ('nit', models.PositiveIntegerField(max_length=9, primary_key=True, serialize=False)),
                ('tel', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
